spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/puke?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: Oyyb258369!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
  servlet:
    context-path: /poker

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cafe.poker.entity
  configuration:
    map-underscore-to-camel-case: true