# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/puke?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Oyyb258369!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.depu.model

# 服务器配置
server.port=8082
server.servlet.context-path=/

# 日志配置
logging.level.com.example.depu=info
